### ISSUE TITLE
NumberFormatException on Ubuntu

### ISSUE THREAD

**Issue by jzarnikov** [profesorfalken/jHardware#3]
`java.lang.NumberFormatException: For input string: "63000
"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.jutils.jhardware.info.processor.unix.UnixProcessorInfo.parseInfo(UnixProcessorInfo.java:68)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:29)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:25)
	at org.jutils.jhardware.HardwareInfo.getProcessorInfo(HardwareInfo.java:48)`

There is a newline character in the temperature String that causes a NumberFormatException.

**Comment by profesorfalken** [comment]
Hi, 
I am planning to perform a big update on jHardware this week and one this is one of the things that will be fixed. 
Thanks for reporting it!

**Comment by profesorfalken** [comment]
Hi again, 
While I prepare the new version I have prepared for you a snapshot version with this fix. You can download it here: 
https://oss.sonatype.org/content/repositories/snapshots/org/jhardware/jHardware/0.6.3-SNAPSHOT/jHardware-0.6.3-20160511.185645-1.jar

Thanks

**Comment by profesorfalken** [comment]
Hello, 

Does it still happen in jHardware 0.8.3?
