### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by OfficialAName** [profesorfalken/jHardware#5]
Whenever i try to use this to my Minecraft plugin server i get this error:

java.lang.NoClassDefFoundError: org/jutils/jhardware/HardwareInfo

**Comment by profesorfalken** [comment]
Hello, 

This is because you have compiled your plugin using this library but you are not providing it in runtime.
You have to add the jar in runtime.

In the case you are using maven, maybe you have set the scope to provided by error?

**Comment by OfficialAName** [comment]
No i didnt, i downloaded your latest jar from the main page of the project and added it to the build path.

**Comment by profesorfalken** [comment]
Hello,
In that case it is necessary why the class cannot be defined. Don't you have the full stacktrace of the error?
Maybe you need to add also a jHardware dependencies as WMI4Java and jPowerShell into the classpath. Try to download and add them: 

https://repo1.maven.org/maven2/com/profesorfalken/WMI4Java/1.4.2/WMI4Java-1.4.2.jar

https://repo1.maven.org/maven2/com/profesorfalken/jPowerShell/1.5/jPowerShell-1.5.jar

**Comment by OfficialAName** [comment]
Still same error as before, even if i added them. 
STACKTRACE:
`org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/jutils/jhardware/HardwareInfo
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NoClassDefFoundError: org/jutils/jhardware/HardwareInfo
	at aname.ro.StopProxy.<init>(StopProxy.java:28) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_92]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.jutils.jhardware.HardwareInfo
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	at aname.ro.StopProxy.<init>(StopProxy.java:28) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_92]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.jar:git-Spigot-5391d73-0ebb9c7]
	... 6 more`


Here is what is at number 28:

`	NetworkInfo network = HardwareInfo.getNetworkInfo();
	MotherboardInfo mb = HardwareInfo.getMotherboardInfo();
	BiosInfo bios = HardwareInfo.getBiosInfo();
	OSInfo os = HardwareInfo.getOSInfo();
	MemoryInfo memory = HardwareInfo.getMemoryInfo();
	ProcessorInfo cpu = HardwareInfo.getProcessorInfo();`

**Comment by OfficialAName** [comment]
*BUMP*

**Comment by OfficialAName** [comment]
@profesorfalken Need some help here?

**Comment by profesorfalken** [comment]
Hi, 

Apparently the classloader of your plugin is not finding & loading the class of jHardware: 

_org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)_

As I said before, the library is not available in runtime so your plugin's classloader cannot load it.

**Comment by OfficialAName** [comment]
i added it in the runtime and still has the same problem, im using eclipse.

**Comment by profesorfalken** [comment]
I do not know anything about minecraft plugin server but... how have you added the library? Have you done as explained here?:  
https://bukkit.org/threads/external-jar-in-project-having-classpath-errors.74043/

**Comment by OfficialAName** [comment]
Yes i added it, and i tried to add it as a project to my plugin too but it wont wooork!.
eclipse --> properties --> build path --> projects --> add
project --> build path --> add external archives --> jHardware

**Comment by profesorfalken** [comment]
With that method you are only adding the jar to the project at compile time, not at runtime. 

Please, try any of the solutions proposed in the link I have posted before.

**Comment by OfficialAName** [comment]
i tried that too but i don't know how to import the classes from "lib" located on the project path.

**Comment by OfficialAName** [comment]
*bump*

**Comment by profesorfalken** [comment]
I am afraid I cannot help you with that since do not know how minecraft plugins work. 

One thing that should always work is to set the libraries in you jre lib directory but of course it is an awful solution.

Anyway, since it is an specific question that applies to any library you want to add to your project, you should ask in a dedicated comunity/forum or take a look at the documentation.
http://wiki.bukkit.org/Main_Page

Good luck
