### ISSUE TITLE
Another NumberFormatException on Linux

### ISSUE THREAD

**Issue by vonkad** [profesorfalken/jHardware#6]
This exception occurs on my linux mint 17.3, ASUS Zenbook.

`Caused by: java.lang.NumberFormatException: For input string: "3400.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.profesorfalken.jsensors.manager.SensorsManager.getSensors(SensorsManager.java:106)
	at com.profesorfalken.jsensors.manager.SensorsManager.getCpu(SensorsManager.java:66)
	at com.profesorfalken.jsensors.manager.SensorsManager.getComponents(SensorsManager.java:54)
	at com.profesorfalken.jsensors.SensorsLocator.getComponents(SensorsLocator.java:34)
	at com.profesorfalken.jsensors.JSensors.components(JSensors.java:73)
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureByjSensors(TemperatureUtils.java:41)
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureForLinux(TemperatureUtils.java:92)
	at org.jutils.jhardware.info.processor.unix.UnixProcessorInfo.parseInfo(UnixProcessorInfo.java:53)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:29)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:25)
	at org.jutils.jhardware.HardwareInfo.getProcessorInfo(HardwareInfo.java:52)
`
it looks like something that you expect to be an int is on my system a float.

**Comment by profesorfalken** [comment]
Hello, 

OK, I will take a look.

Thanks for reporting it!

**Comment by profesorfalken** [comment]
Ok, I have found it. It is a bug in the component jSensors. 

I will try to fix it soon. I will keep you updated!

Regards

**Comment by vonkad** [comment]
Thanks a lot. We use 0.8.1.

**Comment by profesorfalken** [comment]
Done. Now it uses the right version of jSensors which includes the fix for the fan speed.

Could you retest using the 0.8.2?

Regards

**Comment by profesorfalken** [comment]
Hello, 

Do you still has this probleme in 0.8.3?
